site_name: Dokumentacja ICM UW
site_description: Komputery Dużej Mocy w ICM UW
site_author: ICM

theme: 
  logo: 'images/Logo_icm_biale.png'
  name: 'material'
  custom_dir: overrides
  palette:
    primary: 'blue-grey'
    accent: 'green'
  features:
    - search.highlight

plugins:
  - search # necessary for search to work
  - git-revision-date-localized:
      type: date
  - mkdocs-jupyter:
      include_source: True

extra_css:
    - style.css

# https://facelessuser.github.io/pymdown-extensions/

repo_name: ICM-HPC
repo_url: https://git.icm.edu.pl/owu/hpc-docs
edit_uri: "https://git.icm.edu.pl/owu/hpc-docs/edit/master/docs/"

markdown_extensions:
    - attr_list
    - fenced_code
    - codehilite
    - mdx_math
    - admonition
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg

# list of emoji: https://gist.github.com/rxaviers/7360908


extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
- Strona główna: index.md
- Formalności:
    - Kto może być użytkownikiem: O_zasobach_ICM/Formalnosci/uzytkownik.md
    - Warunki korzystania: O_zasobach_ICM/Formalnosci/warunki.md
    - Regulamin użytkownika: O_zasobach_ICM/Formalnosci/regulamin.md
    - (EN) Terms of Service: O_zasobach_ICM/Formalnosci/en_regulamin.md
    - Polityka prywatności: O_zasobach_ICM/Formalnosci/polityka_prywatnosci.md
- Zasoby sprzętowe:
    - Komputery: O_zasobach_ICM/Zasoby/komputery_w_icm.md
    - Przechowywanie danych: O_zasobach_ICM/Zasoby/przechowywanie_danych.md
- Aplikacje:
    - Dostępne oprogramowanie: O_zasobach_ICM/Aplikacje/aplikacje.md
    - Dostępne kompilatory: O_zasobach_ICM/Aplikacje/kompilatory.md
    - CI status: O_zasobach_ICM/Aplikacje/ci_status.md
- Licencje krajowe:
    - ANSYS: Licencje_krajowe/ansys.md
    - Gaussian: Licencje_krajowe/gaussian.md
- Podręcznik grantowy:
    - Zakładanie konta: Podrecznik_grantowy/zakladanie_konta.md
    - Poczta elektroniczna: Podrecznik_grantowy/poczta_elektroniczna.md
    - Jak wystąpić o grant obliczeniowy: Podrecznik_grantowy/jak_wystapic_o_grant_obliczeniowy.md
    - Rodzaje grantów: Podrecznik_grantowy/rodzaje_grantow.md
    - Rozliczanie grantu: Podrecznik_grantowy/rozliczanie_grantu.md

- (EN) Grants User Guide:
    - Creating account: Podrecznik_grantowy/en_zakladanie_konta.md
    - Username and password: Podrecznik_grantowy/en_nazwa_konta_i_haslo.md
    - ICM e-mail: Podrecznik_grantowy/en_poczta_elektroniczna.md
    - Submitting grant application: Podrecznik_grantowy/en_jak_wystapic_o_grant_obliczeniowy.md
    - Okeanos - Call for applications: Podrecznik_grantowy/en_konkurs_okeanos.md
    - Grant owner and members: Podrecznik_grantowy/en_kierownik_oraz_nowi_wspolwykonawcy_grantu.md
    - Reports and publications: Podrecznik_grantowy/en_sprawozdania_i_publikacje_w_grancie.md

- Instrukcje:
  - Logowanie:
    - Nazwa konta i hasło: Tutorials/Logowanie/nazwa_konta_i_haslo.md
    - Logowanie SSH: Tutorials/Logowanie/ssh.md
    - Logowanie SSH (Użytkownicy Windows): Tutorials/Logowanie/ssh_windows.md
    - Tunelowanie SSH: Tutorials/Logowanie/ssh-tunel.md
  - Podstawy HPC:
    - Wstęp: Tutorials/HPC-intro/introduction.md
    - Bash i terminal: Tutorials/HPC-intro/bash_intro.md
    - Kopiowanie plików: Tutorials/HPC-intro/kopiowanie_plikow.md
    - Zlecanie zadań do SLURM: Tutorials/HPC-intro/slurm_intro.md
    - Ustawianie środowiska: Tutorials/HPC-intro/ustawianie_srodowiska.md
    - Instalacja nowego oprogramowania: Tutorials/HPC-intro/instalacja_oprogramowania.md
    - Instalacja oprogramowania - spack: Tutorials/HPC-intro/instalacja_oprogramowania_spack.md
    - Terminal multiplexer: Tutorials/HPC-intro/terminal_multiplexer.md
    - Status zadania: Tutorials/HPC-intro/status_zadania.md
    - Status grantu/konta/qos: Tutorials/HPC-intro/status_grantu_i_konta.md
  - Podstawy GPU:
    - Introduction (Cheat Sheet): Tutorials/GPU-intro/introduction.md
    - Hello World: Tutorials/GPU-intro/hello_world.md
    - Vector Add: Tutorials/GPU-intro/vector_add.md
    - Element-wise Matrix Add: Tutorials/GPU-intro/matrix_addition.md
    - Parallel reduction: Tutorials/GPU-intro/parallel_reduction.md
    - Thrust library: Tutorials/GPU-intro/thrust.md
  - Kontenery:
    - Singularity: Tutorials/Kontenery/singularity_intro.md
  - NEC SX-Aurora Tsubasa:
    - (EN) Basic usage: Tutorials/NEC/en-basic-usage.md
    - (EN) SOL/neural networks: Tutorials/NEC/en-sol.md
    - (PL) Podstawy użycia: Tutorials/NEC/pl-podstawy.md
    - (PL) SOL/sieci neuronowe: Tutorials/NEC/pl-sol.md
  - Środowisko wirtualne:
    - Python: Tutorials/python/python.md
    - Anaconda: Tutorials/python/anaconda.md
- Szkolenia:
  - Informacje: Szkolenia/informacje.md
  - Materiały:
    - Wprowadzenie do obliczeń na komputerach ICM 2021: Szkolenia/intro_icm_2021.md
    - Wprowadzenie do obliczeń na komputerach ICM 2019: Szkolenia/intro_icm_2019.md
    - Wprowadzenie do obliczeń wektorowych – NEC SX-Aurora Tsubasa: Szkolenia/intro_nec.md
    - Effective Neural Networks Without GPU (SOL): Szkolenia/intro_sol.md
    - Obliczenia grafowe i sieciowe:
      - Start: 'Szkolenia/grafy/index.md'
      - Terminy warsztatów: 'Szkolenia/grafy/terminy.md'
      - Wymagania wstępne: 'Szkolenia/grafy/wymagania.md'
      - Warsztaty z Trovares xGT:
        - Materiały wprowadzające: 'Szkolenia/grafy/xgt/materialy-wprowadzajace.md'
        - Agenda warsztatów: 'Szkolenia/grafy/xgt/agenda.md'
        - Prezentacje + Notebooki:
          - Prezentacje:
            - Wprowadzenie: Szkolenia/grafy/xgt/files/presentations/wprowadzenie.pdf
            - Łączenie się po SSH z superkomputerem Rysy: Szkolenia/grafy/xgt/files/presentations/ssh.pdf
            - Część praktyczna: Szkolenia/grafy/xgt/files/presentations/czesc-praktyczna.pdf
          - Jupyter Notebook:
            - Demo - analiza ruchu sieciowego w LANL: Szkolenia/grafy/xgt/files/notebooks/demo.ipynb
            - Hands-on cz. I: Szkolenia/grafy/xgt/files/notebooks/zadania-1.ipynb
            - Hands-on cz. II: Szkolenia/grafy/xgt/files/notebooks/zadania-2.ipynb
      - Warsztaty z Urika-XC Cray Graph Engine:
        - Materiały wprowadzające: 'Szkolenia/grafy/urika-xc/materialy-wprowadzajace.md'
        - Agenda warsztatów: 'Szkolenia/grafy/urika-xc/agenda.md'
        - Materiały:
          - Prezentacja: 'Szkolenia/grafy/urika-xc/files/presentations/warsztaty_cray_graph_engine.pdf'
          - Przygotowanie do działania: 'Szkolenia/grafy/urika-xc/przygotowanie_do_dzialania.md'
          - SPARQL: 'Szkolenia/grafy/urika-xc/sparql.md'
          - S-T Connectivity: 'Szkolenia/grafy/urika-xc/st_connectivity.md'
        - Materiały dodatkowe:
          - Metody użycia CGE: Szkolenia/grafy/urika-xc/metody_uzycia_cge.ipynb
          - Pagerank: Szkolenia/grafy/urika-xc/pagerank.ipynb
      - Kontakt & Organizatorzy: 'Szkolenia/grafy/kontakty.md'
  - Archiwum: Szkolenia/archiwum.md
- Sesje użytkowników KDM:
  - Aktualności: Sesje_KDM/aktualnosci.md
  - Sesja 2021: 
    - Informacje: Sesje_KDM/sesja2021/sesja2021.md
    - Prelegenci: Sesje_KDM/sesja2021/prelegenci.md
  - Archiwum: Sesje_KDM/archiwum.md

- Kontakt: kontakt.md
